#Autostart programs

exec-once = $terminal
exec-once = waybar &
exec-once = $broser
exec-once = nm-applet &
exec-once = hyprpaper &
exec-once = nm-applet --indicator
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
