# Aspect and feel
# https://wiki.hypr.land/Configuring/Variables/#general
general {
    gaps_in = 3
    gaps_out = 4,5
    border_size = 2

    col.active_border = $color2 $color15 45deg
    col.inactive_border = $color14

    resize_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
    rounding = 8
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 0.9
    inactive_opacity = 0.8

    shadow {
        enabled = false
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hypr.land/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        vibrancy = 2
        xray = true
    }
}

layerrule {
    name = blur_logout_dialog

    match:namespace = logout_dialog

    blur = on
}

#Windows rules
#Use "hyprctl clients" to identify windows names, classes or more
windowrule {
  name = windowrule-1
  no_blur = on
  match:class = ^(apphere)$
}

#Animations
animations{
    enabled = true
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    animation = windowsIn, 1, 4, easeOutQuint, popin 100%
    animation = windowsOut, 1, 4, easeOutQuint, popin 100%
    animation = workspaces, 0
    #animation = fadeIn, 1, 4, easeOutQuint
    #animation = fadeOut, 1, 4, easeOutQuint
    #animation = windowsMove, 0
    #animation = workspaces, 1, 4, easeOutQuint, fade
    #animation = fade, 0

}