### Variables ###
$run = uwsm app --
$terminal = $run kitty
$browser = $run brave
$browser2 = $run zen-browser
$fileManager = $run dolphin
$menu = $run wofi --show drun --style ~/.cache/wal/wofi.css
$pmanager = $run bitwarden-desktop
$code_editor = $run zeditor
