# ###################################### #
# ########## HYPRLAND CONFIGS ########## #
# ###################################### #

#Custom configs
source = ~/.cache/wal/hyprland-colors.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/cosmetics.conf
source = ~/.config/hypr/layout.conf
source = ~/.config/hypr/devices.conf

xwayland {
  force_zero_scaling = true
}
