# --- Colores Principales ---
background #1a1112
foreground #f0dedf
cursor #f0dedf
cursor_text_color #1a1112
selection_background #5c3f41
selection_foreground #ffdadc
url_color #e8c08e

# --- Paleta ANSI (Normal / Bright) ---
color0 #1a1112
color1 #ffb4ab
color2 #e8c08e
color3 #e5bdbf
color4 #ffb2b9
color5 #5d411b
color6 #5c3f41
color7 #f0dedf

color8  #524344
color9  #93000a
color10 #5d411b
color11 #5c3f41
color12 #72333b
color13 #5c3f41
color14 #5d411b
color15 #d7c1c2
