# --- Configuración General ---
map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_clipboard

allow_remote_control yes
background_opacity 0.7
enable_background_blur yes
background_blur 1

# --- Colores Principales (Material You) ---
background #111318
foreground #e1e2e9
cursor #a8c8ff
cursor_text_color #05305f
selection_background #254777
selection_foreground #d5e3ff
url_color #dbbce1

# --- Bordes de Ventana (Kitty layouts) ---
active_border_color #a8c8ff
inactive_border_color #43474e

# --- Paleta ANSI Normal (Colores Saturados con Tono) ---
color0 #111318
color1 #ffb4ab
color2 #a8c8ff
color3 #bdc7dc
color4 #dbbce1
color5 #3f5f90
color6 #bdc7dc
color7 #c4c6cf

# --- Paleta ANSI Bright (Acentos Vivos y Legibles) ---
color8  #8e9099
color9  #ffb4ab
color10 #a8c8ff
color11 #bdc7dc
color12 #dbbce1
color13 #3f5f90
color14 #dbbce1
color15 #e1e2e9
