# --- Configuración General ---
map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_clipboard

allow_remote_control yes
background_opacity 0.7
enable_background_blur yes
background_blur 1
font_family JetBrainsMono Nerd Font
font_size 12

# --- Colores Principales (Material You) ---
background #18130b
foreground #ece1d4
cursor #f1be6e
cursor_text_color #432c00
selection_background #614000
selection_foreground #ffddaf
url_color #b6cea3

# --- Bordes de Ventana (Kitty layouts) ---
active_border_color #f1be6e
inactive_border_color #4f4539

# --- Paleta ANSI Normal (Colores Saturados con Tono) ---
color0 #18130b
color1 #ffb4ab
color2 #f1be6e
color3 #dcc3a1
color4 #b6cea3
color5 #7d570e
color6 #dcc3a1
color7 #d2c4b4

# --- Paleta ANSI Bright (Acentos Vivos y Legibles) ---
color8  #9b8f80
color9  #ffb4ab
color10 #f1be6e
color11 #dcc3a1
color12 #b6cea3
color13 #7d570e
color14 #b6cea3
color15 #ece1d4
